export default {
  FIREBASE_API_KEY: import.meta.env.VITE_REACT_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: import.meta.env.VITE_REACT_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: import.meta.env.VITE_REACT_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: import.meta.env.VITE_REACT_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: import.meta.env
    .VITE_REACT_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: import.meta.env.VITE_REACT_FIREBASE_APP_ID,
  FIREBASE_KEY_PAIR_MESSAGING: import.meta.env
    .VITE_REACT_FIREBASE_KEY_PAIR_MESSAGING,
}
